<?php

namespace App\Utils;

class UtilityFunctions
{
    public static function pick_itm_random($array): mixed
    {
        return $array[array_rand($array)];
    }
    
    public static function get_fake_food(): string
    {
        return UtilityFunctions::pick_itm_random([
            "Blue cheese",
            "Burrata",
            "Cheddar",
            "Cream cheese",
            "Feta",
            "Garganzola",
            "Goat cheese",
            "Gouda",
            "Gruyere",
            "Haloumi",
            "Havarti",
            "Mozzarella",
            "Parmesan",
            "Pecorino Romano",
            "Provolone",
            "Ricotta",
            "Anchovies",
            "Bacon",
            "Canadian Bacon",
            "Chicken",
            "Clams",
            "Crab",
            "Ground Beef",
            "Ground Sausage",
            "Ham",
            "Meatballs",
            "Pancetta",
            "Pepperoni",
            "Prosciutto",
            "Salami",
            "Salmon",
            "Scallops",
            "Shredded Pork",
            "Shrimp",
            "Sliced Sausage",
            "Steak",
            "Arugala",
            "Asparagus",
            "Bell peppers",
            "Black olives",
            "Broccoli",
            "Brussel sprouts",
            "Chili peppers",
            "Eggplant",
            "Garlic",
            "Giardiniera",
            "Green olives",
            "Green Olives",
            "Green Onions",
            "Green Peppers",
            "Habanero peppers",
            "Jalapenos",
            "Kale",
            "Mushrooms",
            "Pepperoncini",
            "Potatoes",
            "Red Onions",
            "Rhubarb",
            "Spinach",
            "Squash",
            "Sun-dried tomatoes",
            "Tomatoes",
            "Zucchini",
            "Bananas",
            "Blackberries",
            "Blueberries",
            "Figse",
            "Grapes",
            "Mango",
            "Oranges",
            "Peaches",
            "Pears",
            "Pineapple",
            "Plums",
            "Raspberries",
            "Strawberries",
            "Basil",
            "Cilantro",
            "Fennel",
            "Garlic",
            "Oregano",
            "Paprika",
            "Parsley",
            "Pepper",
            "Rosemary",
            "Sage",
            "Thym",
        ]);
    }
}

?>